# Dependabot configuration for automatic dependency updates
# See: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2

updates:
  # Rust dependencies (Cargo.toml)
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "rust"
    reviewers:
      - "liamhelmer"
    commit-message:
      prefix: "cargo"
      include: "scope"
    # Group minor and patch updates
    groups:
      rust-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Frontend dependencies (package.json)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "frontend"
    reviewers:
      - "liamhelmer"
    commit-message:
      prefix: "npm"
      include: "scope"
    # Ignore major version updates for stable dependencies
    ignore:
      - dependency-name: "xterm"
        update-types: ["version-update:semver-major"]
    # Group minor and patch updates
    groups:
      frontend-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
    reviewers:
      - "liamhelmer"
    commit-message:
      prefix: "ci"
      include: "scope"
    # Group all GitHub Actions updates
    groups:
      github-actions:
        patterns:
          - "*"

  # Docker base images
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "docker"
    reviewers:
      - "liamhelmer"
    commit-message:
      prefix: "docker"
      include: "scope"