# Cargo configuration
# Per spec-kit/003-backend-spec.md

[build]
# Use all available CPU cores for building (omit jobs for auto-detection)
# jobs = 0 causes error, so we let cargo auto-detect

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

# Optimizations for faster builds in development
[profile.dev]
opt-level = 0
debug = true
incremental = true

# Fast compilation profile for CI
[profile.dev.package."*"]
opt-level = 3
debug = false

# Build dependencies with optimizations even in dev mode
[profile.dev.build-override]
opt-level = 3

# Alias for commonly used commands
[alias]
xtask = "run --package xtask --"
watch = "watch -x run"